#version: '3.8'
#
#services:
#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.5.0
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      - "2181:2181"
#
#  kafka:
#    image: confluentinc/cp-kafka:7.5.0
#    depends_on:
#      - zookeeper
#    ports:
#      - "9092:9092"
#      - "9094:9094"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENERS: PLAINTEXT_HOST://0.0.0.0:9092,PLAINTEXT://0.0.0.0:29092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://10.39.18.100:9092,PLAINTEXT://kafka:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#
#  schema-registry:
#    image: confluentinc/cp-schema-registry:7.5.0
#    depends_on:
#      - kafka
#    ports:
#      - "8081:8081"
#    environment:
#      SCHEMA_REGISTRY_HOST_NAME: schema-registry
#      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081/
#      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
#
#  postgres:
#    image: postgres:15
#    container_name: vehicle_postgres
#    environment:
#      POSTGRES_DB: vehicle_reservation
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 1234
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#  consumer:
#    build:
#      context: .
#    container_name: vehicle_reservation_consumer
#    depends_on:
#      - kafka
#      - postgres
#      - schema-registry
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vehicle_reservation
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: 1234
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry:8081/
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#      SPRING_JPA_SHOW_SQL: "true"
#
#volumes:
#  postgres_data:

#version: '3.8'
#
#services:
#  postgres:
#    image: postgres:14
#    restart: always
#    environment:
#      POSTGRES_DB: vehicle_reservation
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 1234
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#  consumer:
#    build: .
#    depends_on:
#      - postgres
#    ports:
#      - "8081:8081"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vehicle_reservation
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: 1234
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: 10.10.4.133:29092
#      SPRING_KAFKA_CONSUMER_GROUP_ID: booking-group
#      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://10.10.4.133:8081
##    networks:
##      - host
#
#volumes:
#  pgdata:

#networks:
#   host:
#     external: true