#spring.application.name=vehicle-reservation-consumer
#
#spring.datasource.url=jdbc:postgresql://postgres:5432/vehicle_reservation
##spring.datasource.url=jdbc:postgresql://localhost:5432/vehicle_reservation
#spring.datasource.username=postgres
#spring.datasource.password=1234
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
##spring.datasource.driver-class-name=org.postgresql.Driver
#
## JPA Configuration
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
## Kafka Configuration
#spring.kafka.bootstrap-servers=kafka:9092
##spring.kafka.bootstrap-servers=10.39.18.100:9092
#spring.kafka.consumer.group-id=booking-group
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
##spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
#spring.kafka.properties.specific.avro.reader=true
#spring.kafka.admin.auto-create=true
#spring.kafka.consumer.auto-offset-reset=latest
#spring.kafka.listener.auto-startup=true
#
#spring.kafka.properties.schema.registry.url=http://schema-registry:8081
#

spring.application.name=vehicle-reservation-consumer
server.port=8081
spring.datasource.url=jdbc:postgresql://postgres:5432/vehicle_reservation
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka Consumer
spring.kafka.bootstrap-servers=10.10.4.133:29092
spring.kafka.consumer.group-id=booking-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer

# Proper Avro deserializer delegation
spring.kafka.properties.spring.deserializer.value.delegate.class=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.properties.specific.avro.reader=true

spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.listener.auto-startup=true
spring.kafka.properties.schema.registry.url=http://10.10.4.133:8081